version: "3"

services:
  backend:
    build:
      context: .
    depends_on:
      - psql
    volumes:
      - static:/var/app/static
      - ./app/:/var/app/
    env_file:
      - .env
    restart: on-failure
    command: bash -c 'python3 manage.py collectstatic --no-input --clear ; python3 manage.py migrate; uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload'
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  redis:
    image: redis:alpine
    expose:
      - 6379
    volumes:
      - "redis_data:/data"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  psql:
    image: postgres:latest
    volumes:
      - psql_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  nginx:
    command: nginx -g 'daemon off;'
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/var/app/static
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "80:80"

volumes:
  psql_data: {}
  static: {}
  redis_data: {}
