# Generated by Django 5.0.5 on 2024-09-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Почта')),
                ('password', models.CharField(blank=True, max_length=254, null=True, verbose_name='Пароль')),
                ('host', models.CharField(blank=True, max_length=254, null=True, verbose_name='Хост')),
                ('last_parse', models.DateTimeField(blank=True, null=True)),
                ('start_parse', models.BooleanField(default=False)),
                ('message_action', models.CharField(blank=True, choices=[('MESSAGE_LOAD', 'Messages load'), ('MESSAGE_SEARCH', 'Messages search')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Email аккаунт',
                'verbose_name_plural': 'Email аккаунты',
            },
        ),
        migrations.CreateModel(
            name='EmailFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('message_uid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Фаийл',
                'verbose_name_plural': 'Фаийлы',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_big_text', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email сообщене',
                'verbose_name_plural': 'Email сообщения',
            },
        ),
    ]
